// Canonical seed dataset for yarn db:seed / db:seed:staging / db:seed:production and unit tests.

export const categories = [
  {
    id: 24,
    name: "income da lavoro",
    slug: "income-da-lavoro",
    type: "in",
    displayOrder: 0,
    isActive: true,
  },
  {
    id: 6,
    name: "pensioni e sussidi",
    slug: "pensioni-e-sussidi",
    type: "in",
    displayOrder: 0,
    isActive: true,
  },
  {
    id: 25,
    name: "rendite",
    slug: "rendite",
    type: "in",
    displayOrder: 0,
    isActive: true,
  },
  {
    id: 26,
    name: "entrate straordinarie",
    slug: "entrate-straordinarie",
    type: "in",
    displayOrder: 0,
    isActive: true,
  },
  {
    id: 7,
    name: "trasporti",
    slug: "trasporti",
    type: "out",
    displayOrder: 0,
    isActive: true,
  },
  {
    id: 8,
    name: "spesa",
    slug: "spesa",
    type: "out",
    displayOrder: 0,
    isActive: true,
  },
  {
    id: 9,
    name: "salute",
    slug: "salute",
    type: "out",
    displayOrder: 0,
    isActive: true,
  },
  {
    id: 13,
    name: "utenze",
    slug: "utenze",
    type: "out",
    displayOrder: 0,
    isActive: true,
  },
  {
    id: 19,
    name: "casa",
    slug: "casa",
    type: "out",
    displayOrder: 0,
    isActive: true,
  },
  {
    id: 15,
    name: "imposte e oneri",
    slug: "imposte-e-oneri",
    type: "out",
    displayOrder: 0,
    isActive: true,
  },
  {
    id: 16,
    name: "servizi professionali",
    slug: "servizi-professionali",
    type: "out",
    displayOrder: 0,
    isActive: true,
  },
  {
    id: 21,
    name: "formazione",
    slug: "formazione",
    type: "out",
    displayOrder: 0,
    isActive: true,
  },
  {
    id: 4,
    name: "vacanze",
    slug: "vacanze",
    type: "out",
    displayOrder: 0,
    isActive: true,
  },
  {
    id: 5,
    name: "regali e donazioni",
    slug: "regali-e-donazioni",
    type: "out",
    displayOrder: 0,
    isActive: true,
  },
  {
    id: 10,
    name: "ristorazione",
    slug: "ristorazione",
    type: "out",
    displayOrder: 0,
    isActive: true,
  },
  {
    id: 11,
    name: "shopping",
    slug: "shopping",
    type: "out",
    displayOrder: 0,
    isActive: true,
  },
  {
    id: 22,
    name: "cultura e tempo libero",
    slug: "cultura-e-tempo-libero",
    type: "out",
    displayOrder: 0,
    isActive: true,
  },
  {
    id: 33,
    name: "benessere",
    slug: "benessere",
    type: "out",
    displayOrder: 0,
    isActive: true,
  },
  {
    id: 17,
    name: "animali",
    slug: "animali",
    type: "out",
    displayOrder: 0,
    isActive: true,
  },
  {
    id: 14,
    name: "rate e finanziamenti",
    slug: "rate-e-finanziamenti",
    type: "out",
    displayOrder: 0,
    isActive: true,
  },
  {
    id: 1,
    name: "risparmio",
    slug: "risparmio",
    type: "out",
    displayOrder: 0,
    isActive: true,
  },
  {
    id: 12,
    name: "investimenti",
    slug: "investimenti",
    type: "out",
    displayOrder: 0,
    isActive: true,
  },
  {
    id: 32,
    name: "trasferimenti",
    slug: "trasferimenti",
    type: "system",
    displayOrder: 0,
    isActive: true,
  },
]

export const subCategories = [
  {
    categoryId: 24,
    name: "stipendio base",
    slug: "stipendio-base",
    natureId: 1,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 24,
    name: "indennità",
    slug: "indennita",
    natureId: 1,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 24,
    name: "bonus",
    slug: "bonus",
    natureId: 2,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 24,
    name: "freelance",
    slug: "freelance",
    natureId: 2,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 24,
    name: "consulenze",
    slug: "consulenze",
    natureId: 2,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 24,
    name: "progetti occasionali",
    slug: "progetti-occasionali",
    natureId: 2,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 24,
    name: "commissioni",
    slug: "commissioni",
    natureId: 2,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 6,
    name: "pensione",
    slug: "pensione",
    natureId: 1,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 6,
    name: "sussidi statali",
    slug: "sussidi-statali",
    natureId: 1,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 25,
    name: "dividendi",
    slug: "dividendi",
    natureId: 1,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 25,
    name: "interessi attivi",
    slug: "interessi-attivi",
    natureId: 1,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 25,
    name: "canone di locazione",
    slug: "canone-di-locazione",
    natureId: 1,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 26,
    name: "cashback",
    slug: "cashback",
    natureId: 2,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 26,
    name: "bonus promozionale",
    slug: "bonus-promozionale",
    natureId: 2,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 26,
    name: "vendita beni usati",
    slug: "vendita-beni-usati",
    natureId: 2,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 26,
    name: "eredità e donazioni",
    slug: "eredita-e-donazioni",
    natureId: 2,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 7,
    name: "carburante e ricarica",
    slug: "carburante-e-ricarica",
    natureId: 3,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 7,
    name: "manutenzione auto",
    slug: "manutenzione-auto",
    natureId: 3,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 7,
    name: "mezzi pubblici",
    slug: "mezzi-pubblici",
    natureId: 3,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 7,
    name: "taxi e ride sharing",
    slug: "taxi-e-ride-sharing",
    natureId: 3,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 7,
    name: "pedaggi e parcheggi",
    slug: "pedaggi-e-parcheggi",
    natureId: 3,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 7,
    name: "assicurazione veicoli",
    slug: "assicurazione-veicoli",
    natureId: 3,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 8,
    name: "spesa quotidiana",
    slug: "spesa-quotidiana",
    natureId: 3,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 8,
    name: "casalinghi e non alimentari",
    slug: "casalinghi-e-non-alimentari",
    natureId: 3,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 8,
    name: "bio vino e gourmet",
    slug: "bio-vino-e-gourmet",
    natureId: 4,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 9,
    name: "visite mediche",
    slug: "visite-mediche",
    natureId: 3,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 9,
    name: "trattamenti medici",
    slug: "trattamenti-medici",
    natureId: 3,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 9,
    name: "farmaci",
    slug: "farmaci",
    natureId: 3,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 9,
    name: "assicurazione salute",
    slug: "assicurazione-salute",
    natureId: 4,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 13,
    name: "energia elettrica",
    slug: "energia-elettrica",
    natureId: 3,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 13,
    name: "gas",
    slug: "gas",
    natureId: 3,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 13,
    name: "acqua",
    slug: "acqua",
    natureId: 3,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 13,
    name: "rifiuti",
    slug: "rifiuti",
    natureId: 3,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 13,
    name: "telefono e internet",
    slug: "telefono-e-internet",
    natureId: 3,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 19,
    name: "affitto",
    slug: "affitto",
    natureId: 3,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 19,
    name: "spese condominiali",
    slug: "spese-condominiali",
    natureId: 3,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 19,
    name: "manutenzione casa",
    slug: "manutenzione-casa",
    natureId: 3,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 19,
    name: "servizi domestici",
    slug: "servizi-domestici",
    natureId: 3,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 19,
    name: "assicurazione casa",
    slug: "assicurazione-casa",
    natureId: 3,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 15,
    name: "imposte",
    slug: "imposte",
    natureId: 3,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 15,
    name: "bolli auto",
    slug: "bolli-auto",
    natureId: 3,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 15,
    name: "multe e sanzioni",
    slug: "multe-e-sanzioni",
    natureId: 3,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 15,
    name: "commissioni e canone conto",
    slug: "commissioni-e-canone-conto",
    natureId: 3,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 16,
    name: "spese legali notarili",
    slug: "spese-legali-notarili",
    natureId: 3,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 21,
    name: "università",
    slug: "universita",
    natureId: 3,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 21,
    name: "spese scolastiche",
    slug: "spese-scolastiche",
    natureId: 3,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 21,
    name: "corsi",
    slug: "corsi",
    natureId: 4,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 4,
    name: "alloggio",
    slug: "alloggio",
    natureId: 4,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 4,
    name: "trasporto",
    slug: "trasporto",
    natureId: 4,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 4,
    name: "attività e intrattenimento",
    slug: "attivita-e-intrattenimento",
    natureId: 4,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 4,
    name: "cibo e bevande",
    slug: "cibo-e-bevande",
    natureId: 4,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 4,
    name: "assicurazione viaggio",
    slug: "assicurazione-viaggio",
    natureId: 4,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 5,
    name: "regali",
    slug: "regali",
    natureId: 4,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 5,
    name: "donazioni beneficenza",
    slug: "donazioni-beneficenza",
    natureId: 4,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 10,
    name: "ristoranti",
    slug: "ristoranti",
    natureId: 4,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 10,
    name: "bar caffè e snack",
    slug: "bar-caffe-e-snack",
    natureId: 4,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 10,
    name: "take away e delivery",
    slug: "take-away-e-delivery",
    natureId: 4,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 11,
    name: "elettronica",
    slug: "elettronica",
    natureId: 4,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 11,
    name: "abbigliamento e accessori",
    slug: "abbigliamento-e-accessori",
    natureId: 4,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 11,
    name: "prodotti per la casa",
    slug: "prodotti-per-la-casa",
    natureId: 4,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 11,
    name: "giocattoli",
    slug: "giocattoli",
    natureId: 4,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 22,
    name: "cinema ed eventi",
    slug: "cinema-ed-eventi",
    natureId: 4,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 22,
    name: "libri e audiolibri",
    slug: "libri-e-audiolibri",
    natureId: 4,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 22,
    name: "streaming",
    slug: "streaming",
    natureId: 4,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 22,
    name: "app e software",
    slug: "app-e-software",
    natureId: 4,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 22,
    name: "videogiochi",
    slug: "videogiochi",
    natureId: 4,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 33,
    name: "sport e fitness",
    slug: "sport-e-fitness",
    natureId: 4,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 33,
    name: "attrezzatura e abbigliamento sportivo",
    slug: "attrezzatura-e-abbigliamento-sportivo",
    natureId: 4,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 33,
    name: "cura della persona",
    slug: "cura-della-persona",
    natureId: 4,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 33,
    name: "psicologia",
    slug: "psicologia",
    natureId: 4,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 17,
    name: "cura animali",
    slug: "cura-animali",
    natureId: 4,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 17,
    name: "assicurazione animali",
    slug: "assicurazione-animali",
    natureId: 4,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 14,
    name: "mutuo casa",
    slug: "mutuo-casa",
    natureId: 5,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 14,
    name: "finanziamenti auto",
    slug: "finanziamenti-auto",
    natureId: 5,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 14,
    name: "altri finanziamenti",
    slug: "altri-finanziamenti",
    natureId: 5,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 1,
    name: "conto risparmio",
    slug: "conto-risparmio",
    natureId: 7,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 1,
    name: "fondo emergenze",
    slug: "fondo-emergenze",
    natureId: 7,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 1,
    name: "accantonamenti obiettivi",
    slug: "accantonamenti-obiettivi",
    natureId: 7,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 12,
    name: "titoli e fondi",
    slug: "titoli-e-fondi",
    natureId: 8,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 12,
    name: "criptovalute",
    slug: "criptovalute",
    natureId: 8,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 12,
    name: "immobili",
    slug: "immobili",
    natureId: 8,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 12,
    name: "previdenza complementare",
    slug: "previdenza-complementare",
    natureId: 8,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 12,
    name: "polizze vita",
    slug: "polizze-vita",
    natureId: 8,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 12,
    name: "oro e beni rifugio",
    slug: "oro-e-beni-rifugio",
    natureId: 8,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 32,
    name: "trasferimento tra conti",
    slug: "trasferimento-tra-conti",
    natureId: 6,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 32,
    name: "addebito carta di credito",
    slug: "addebito-carta-di-credito",
    natureId: 6,
    displayOrder: 0,
    isActive: true,
  },
  {
    categoryId: 32,
    name: "contante",
    slug: "contante",
    natureId: 6,
    displayOrder: 0,
    isActive: true,
  },
]

// ---------------------------------------------------------------------------
// PLATFORMS
// ---------------------------------------------------------------------------

export type AmountType = "single" | "separate";

export const platforms = [
  {
    id: 1,
    name: "General",
    slug: "general",
    // ISO 3166-1 alpha-2 placeholder for the catch-all import format.
    // The platform.country column is varchar(2), so values must remain two characters.
    country: "ZZ",
    delimiter: ",",
    descriptionColumn: "description",
    amountType: "single" as AmountType,
    amountColumn: "amount",
    positiveAmountColumn: null,
    negativeAmountColumn: null,
    timestampColumn: "timestamp",
    dateFormat: null,
    dateReplace: false,
    decimalReplace: false,
    multiplyBy: 1,
  },
  {
    id: 2,
    name: "Crypto.com",
    slug: "crypto-com",
    country: "IT",
    delimiter: ",",
    descriptionColumn: "Transaction Description",
    amountType: "single" as AmountType,
    amountColumn: "Amount",
    positiveAmountColumn: null,
    negativeAmountColumn: null,
    timestampColumn: "Timestamp (UTC)",
    dateFormat: null,
    dateReplace: false,
    decimalReplace: false,
    multiplyBy: 1,
  },
  {
    id: 3,
    name: "Satispay",
    slug: "satispay",
    country: "IT",
    delimiter: ",",
    descriptionColumn: "Nome",
    amountType: "single" as AmountType,
    amountColumn: "Importo",
    positiveAmountColumn: null,
    negativeAmountColumn: null,
    timestampColumn: "Data",
    dateFormat: "DD MMM YYYY. HH:mm:ss",
    dateReplace: true,
    decimalReplace: false,
    multiplyBy: 1,
  },
  {
    id: 4,
    name: "Intesa SP",
    slug: "intesa-sp",
    country: "IT",
    delimiter: ",",
    descriptionColumn: "Operazione",
    amountType: "single" as AmountType,
    amountColumn: "Importo",
    positiveAmountColumn: null,
    negativeAmountColumn: null,
    timestampColumn: "Data",
    dateFormat: "DD-MM-YYYY",
    dateReplace: true,
    decimalReplace: true,
    multiplyBy: 1,
  },
  {
    id: 5,
    name: "Intesa SP Carta Credito",
    slug: "intesa-sp-carta-credito",
    country: "IT",
    delimiter: ",",
    descriptionColumn: "Descrizione",
    amountType: "single" as AmountType,
    amountColumn: "Addebiti",
    positiveAmountColumn: null,
    negativeAmountColumn: null,
    timestampColumn: "Data operazione",
    dateFormat: "DD/MM/YYYY",
    dateReplace: true,
    decimalReplace: true,
    multiplyBy: -1,
  },
  {
    id: 6,
    name: "Revolut",
    slug: "revolut",
    country: "IT",
    delimiter: ",",
    descriptionColumn: "Description",
    amountType: "single" as AmountType,
    amountColumn: "Amount",
    positiveAmountColumn: null,
    negativeAmountColumn: null,
    timestampColumn: "Completed Date",
    dateFormat: null,
    dateReplace: false,
    decimalReplace: false,
    multiplyBy: 1,
  },
  {
    id: 7,
    name: "Fineco",
    slug: "fineco",
    country: "IT",
    delimiter: ",",
    descriptionColumn: "Descrizione_Completa",
    amountType: "separate" as AmountType,
    amountColumn: null,
    positiveAmountColumn: "Entrate",
    negativeAmountColumn: "Uscite",
    timestampColumn: "Data",
    dateFormat: "DD/MM/YYYY",
    dateReplace: true,
    decimalReplace: false,
    multiplyBy: 1,
  },
];

// ---------------------------------------------------------------------------
// CATEGORIZATION PATTERNS (regex sistema, userId = null)
// ---------------------------------------------------------------------------

export type AmountSign = "positive" | "negative" | "any";

export const categorizationPatterns = [
  {
    pattern:
      "(?:\\bcoop\\b|\\bnova coop\\b|\\bmercato big\\b|\\bmercatò\\b|mercato.*local|\\besselunga\\b|\\bcarrefour\\b|\\bconad\\b|\\bpam\\b|\\btigre\\b|\\biper\\b|\\bsupermercato\\b|\\bsuper\\b|\\bmarket\\b|\\bcrai\\b|\\blidl\\b|\\beurospin\\b|\\bmd\\b|\\baldi\\b|\\bdespar\\b|\\beurospar\\b|\\binterspar\\b|\\bipercoop\\b|\\bbennet\\b|\\bil gigante\\b|\\bunes\\b|\\bu2\\b|\\bu!\\b|\\bfamila\\b|\\bsisa\\b|\\bsigma\\b|\\btodis\\b|\\bpewex\\b|\\biperal\\b)",
    subCategorySlug: "supermercato",
    amountSign: "negative" as AmountSign,
    confidence: 0.95,
    priority: 10,
    description: "Supermarkets and grocery stores",
  },
  {
    pattern:
      "(?:\\bmacelleria\\b|\\bmacellaio\\b|\\bpescheria\\b|\\bpescivendolo\\b|\\bittic[oa]\\b|\\bortofrutta\\b|\\bortofrutt[ai]\\b|\\bfrutta e verdura\\b|\\bfruttivendolo\\b|\\bpanificio\\b|\\bpanetteria\\b|\\bforno\\b|\\bfornaio\\b|\\bgastronomia\\b|\\brosticceria\\b|\\bsalumeria\\b|\\bsalumiere\\b|\\bcaseificio\\b|\\blatticin[io]\\b|\\blatticini\\b|\\bformaggi\\b)",
    subCategorySlug: "negozio-di-quartiere",
    amountSign: "negative" as AmountSign,
    confidence: 0.9,
    priority: 15,
    description: "Negozi specializzati in prodotti freschi",
  },
  {
    pattern: "(?:\\bamazon\\b|\\bamzn\\b)",
    subCategorySlug: "elettronica",
    amountSign: "negative" as AmountSign,
    confidence: 0.9,
    priority: 20,
    description: "Amazon purchases",
  },
  {
    pattern:
      "(?:\\bmcdonald\\b|\\bburger king\\b|\\bkfc\\b|\\bpizza\\b|\\bristorante\\b|\\btrattoria\\b|\\bosteria\\b|\\bpizzeria\\b)",
    subCategorySlug: "cene-fuori",
    amountSign: "negative" as AmountSign,
    confidence: 0.9,
    priority: 30,
    description: "Restaurants and fast food",
  },
  {
    pattern:
      "(?:\\bstarbucks\\b|\\bbar\\b|(?:^|[^a-zA-Z])caff(?:e|è|é|e[''`])(?:[^a-zA-Z]|$)|\\bcaffetteria\\b|\\bcoffee\\b|\\bespresso\\b)",
    subCategorySlug: "colazioni-e-snack",
    amountSign: "negative" as AmountSign,
    confidence: 0.85,
    priority: 40,
    description: "Bars and coffee shops",
  },
  {
    pattern: "(?:\\bpasticceria\\b|\\bpasticcerie\\b)",
    subCategorySlug: "colazioni-e-snack",
    amountSign: "negative" as AmountSign,
    confidence: 0.9,
    priority: 35,
    description: "Pasticcerie e dolci",
  },
  {
    pattern: "(?:\\beni\\b.*\\bplenitude\\b|\\bplenitude\\b)",
    subCategorySlug: "energia-elettrica",
    amountSign: "negative" as AmountSign,
    confidence: 0.95,
    priority: 5,
    description: "Eni Plenitude - Electricity",
  },
  {
    pattern:
      "(?:\\benel\\b|\\benel energia\\b|\\ba2a\\b|\\bedison\\b|\\bluce\\b|\\belettricità\\b|\\bgas\\b|\\bacqua\\b)",
    subCategorySlug: "energia-elettrica",
    amountSign: "negative" as AmountSign,
    confidence: 0.9,
    priority: 10,
    description: "Energy and utility providers",
  },
  {
    pattern:
      "(?:\\beni\\b(?!.*plenitude)|\\besso\\b|\\bshell\\b|\\bq8\\b|\\btamoil\\b|\\bcarburante\\b|\\bbenzina\\b|\\bdiesel\\b|\\bgasolio\\b)",
    subCategorySlug: "carburante",
    amountSign: "negative" as AmountSign,
    confidence: 0.95,
    priority: 10,
    description: "Gas stations and fuel",
  },
  {
    pattern:
      "(?:\\btrenitalia\\b|\\bitalo\\b|\\bfrecciarossa\\b|\\bfrecciargento\\b|\\bfrecciabianca\\b|\\btreno\\b|\\bferrovie\\b)",
    subCategorySlug: "treno",
    amountSign: "negative" as AmountSign,
    confidence: 0.95,
    priority: 5,
    description: "Railway services and trains",
  },
  {
    pattern:
      "(?:\\batm\\b|\\bautostrada\\b|\\btelepass\\b|\\bpedaggio\\b|\\bviacard\\b)",
    subCategorySlug: "pedaggi-autostradali",
    amountSign: "negative" as AmountSign,
    confidence: 0.9,
    priority: 20,
    description: "Highway tolls and telepass",
  },
  {
    pattern: "(?:\\buber\\b|\\btaxi\\b|\\bbolt\\b|\\bfreenow\\b)",
    subCategorySlug: "taxi-e-ride-sharing",
    amountSign: "negative" as AmountSign,
    confidence: 0.9,
    priority: 30,
    description: "Shared transport services",
  },
  {
    pattern:
      "(?:\\bnetflix\\b|\\bdisney\\+?\\b|\\bprime video\\b|\\bamazon prime video\\b|\\bnow tv\\b|\\bnow\\b|\\bapple tv\\+?\\b|\\braiplay\\b|\\bmediaset infinity\\b|\\bdazn\\b|\\bparamount\\+?\\b|\\bsky go\\b|\\bdiscovery\\+?\\b|\\byoutube premium\\b)",
    subCategorySlug: "streaming-video",
    amountSign: "negative" as AmountSign,
    confidence: 0.95,
    priority: 10,
    description: "Video streaming services",
  },
  {
    pattern:
      "(?:\\bspotify\\b|\\bapple music\\b|\\bamazon music\\b|\\bdeezer\\b|\\btidal\\b|\\byoutube music\\b)",
    subCategorySlug: "streaming-musica",
    amountSign: "negative" as AmountSign,
    confidence: 0.95,
    priority: 10,
    description: "Music streaming services",
  },
  {
    pattern: "(?:\\bfarmacia\\b|\\bpharmacy\\b|\\bparafarmacia\\b)",
    subCategorySlug: "farmaci-generici",
    amountSign: "negative" as AmountSign,
    confidence: 0.9,
    priority: 20,
    description: "Pharmacies and parapharmacies",
  },
  {
    pattern:
      "(?:\\bospedale\\b|\\bclinica\\b|\\bmedico\\b|\\bdottore\\b|\\bvisita\\b|\\banalisi\\b)",
    subCategorySlug: "visite-mediche",
    amountSign: "negative" as AmountSign,
    confidence: 0.85,
    priority: 30,
    description: "Medical visits and healthcare facilities",
  },
  {
    pattern:
      "(?:\\bpalestra\\b|\\bgym\\b|\\bfitness\\b|\\bpiscina\\b|\\bsport\\b|\\bpadel\\b|\\btennis\\b)",
    subCategorySlug: "sport",
    amountSign: "negative" as AmountSign,
    confidence: 0.9,
    priority: 35,
    description: "Sport: palestre, padel, tennis, fitness, piscine",
  },
  {
    pattern: "canone mensile",
    subCategorySlug: "altri-abbonamenti",
    amountSign: "negative" as AmountSign,
    confidence: 0.9,
    priority: 10,
    description: "Canoni mensili vari",
  },
  {
    pattern:
      "(?:\\bvodafone\\b|\\btim\\b|\\bwind\\b|\\bwindtre\\b|\\biliad\\b|\\bfastweb\\b|\\bposte ?mobile\\b|\\bcoop ?voce\\b|\\bho ?mobile\\b|\\bho\\.\\b|\\bvery ?mobile\\b|\\bkena\\b|\\btiscali\\b|\\bsky wifi\\b|\\bsky mobile\\b|\\bspusu\\b|\\blycamobile\\b)",
    subCategorySlug: "servizi-telefonici-e-internet",
    amountSign: "negative" as AmountSign,
    confidence: 0.95,
    priority: 5,
    description: "Operatori telefonici in Italia",
  },
  {
    pattern: "bonifico",
    subCategorySlug: "bonifico-in-uscita",
    amountSign: "negative" as AmountSign,
    confidence: 0.95,
    priority: 10,
    description: "Bonifici in uscita",
  },
  {
    pattern: "bonifico",
    subCategorySlug: "bonifico-in-entrata",
    amountSign: "positive" as AmountSign,
    confidence: 0.95,
    priority: 10,
    description: "Bonifici in entrata",
  },
  {
    pattern:
      "(?:commissioni?.*spese.*adue|commissione.*disposizione.*bonifico|commissione.*bonifico)",
    subCategorySlug: "commissioni-bancarie",
    amountSign: "negative" as AmountSign,
    confidence: 0.95,
    priority: 10,
    description: "Commissioni bancarie",
  },
  {
    pattern: "addebito diretto.*volkswagen",
    subCategorySlug: "finanziamenti-auto",
    amountSign: "negative" as AmountSign,
    confidence: 0.95,
    priority: 5,
    description: "Rate Volkswagen Bank",
  },
  {
    pattern: "addebito diretto.*fca bank",
    subCategorySlug: "finanziamenti-auto",
    amountSign: "negative" as AmountSign,
    confidence: 0.95,
    priority: 5,
    description: "Rate FCA Bank",
  },
  {
    pattern: "addebito diretto.*disposto.*favore",
    subCategorySlug: "altri-finanziamenti",
    amountSign: "negative" as AmountSign,
    confidence: 0.8,
    priority: 20,
    description: "Addebiti diretti per finanziamenti vari",
  },
  {
    pattern: "(?:stipendio.*pensione|^stipendio$|^pensione$)",
    subCategorySlug: "stipendio-base",
    amountSign: "positive" as AmountSign,
    confidence: 0.95,
    priority: 5,
    description: "Stipendi e pensioni",
  },
  {
    pattern: "(?:^|[^a-z0-9])pago\\s*pa(?:[^a-z0-9]|$)",
    subCategorySlug: "imposte",
    amountSign: "any" as AmountSign,
    confidence: 0.75,
    priority: 90,
    description: "PagoPA - da classificare manualmente",
  },
  {
    pattern:
      "(?:\\bfocacceria\\b|\\bpizza\\s*al\\s*taglio\\b|\\brosticceria\\b|\\btavola\\s*calda\\b|\\bpaninoteca\\b|\\bgastronomia\\b)",
    subCategorySlug: "take-away",
    amountSign: "negative" as AmountSign,
    confidence: 0.9,
    priority: 35,
    description: "Take away: focaccerie, pizza al taglio, rosticcerie",
  },
  {
    pattern:
      "(?:\\bdeliveroo\\b|\\bjust\\s*eat\\b|\\bglovo\\b|\\bwolt\\b)",
    subCategorySlug: "take-away",
    amountSign: "negative" as AmountSign,
    confidence: 0.95,
    priority: 25,
    description: "Delivery app orders",
  },
];

// ---------------------------------------------------------------------------
// DIRECTIONS (lookup table — 4 static rows: in | out | allocation | transfer)
// ---------------------------------------------------------------------------

export type NetWorthEffect = "increase" | "decrease" | "neutral";

export const directions = [
  {
    id: 1,
    code: "in",
    labelIt: "Entrate",
    netWorthEffect: "increase" as NetWorthEffect,
    includedInTotals: true,
    shownSeparately: false,
    hidden: false,
    displayOrder: 0,
    color: "#34d399",
  },
  {
    id: 2,
    code: "out",
    labelIt: "Uscite",
    netWorthEffect: "decrease" as NetWorthEffect,
    includedInTotals: true,
    shownSeparately: false,
    hidden: false,
    displayOrder: 1,
    color: "#f97316",
  },
  {
    id: 3,
    code: "allocation",
    labelIt: "Accantonamenti",
    netWorthEffect: "neutral" as NetWorthEffect,
    includedInTotals: false,
    shownSeparately: true,
    hidden: false,
    displayOrder: 2,
    color: "#a78bfa",
  },
  {
    id: 4,
    code: "transfer",
    labelIt: "Trasferimenti",
    netWorthEffect: "neutral" as NetWorthEffect,
    includedInTotals: false,
    shownSeparately: false,
    hidden: true,
    displayOrder: 3,
    color: "#94a3b8",
  },
];

// ---------------------------------------------------------------------------
// NATURES (lookup table — 8 rows per D-01; each row references a direction id)
// ---------------------------------------------------------------------------

export const natures = [
  {
    id: 1,
    code: "income",
    directionId: 1,
    labelIt: "Entrate ricorrenti",
    color: "#34d399",
    displayOrder: 0,
  },
  {
    id: 2,
    code: "income_extraordinary",
    directionId: 1,
    labelIt: "Straordinaria",
    color: "#a7f3d0",
    displayOrder: 1,
  },
  {
    id: 3,
    code: "essential",
    directionId: 2,
    labelIt: "Essenziale",
    color: "#4ade80",
    displayOrder: 2,
  },
  {
    id: 4,
    code: "discretionary",
    directionId: 2,
    labelIt: "Discrezionale",
    color: "#f97316",
    displayOrder: 3,
  },
  {
    id: 5,
    code: "debt",
    directionId: 2,
    labelIt: "Debiti",
    color: "#f87171",
    displayOrder: 4,
  },
  {
    id: 6,
    code: "transfer",
    directionId: 4,
    labelIt: "Trasferimento",
    color: "#94a3b8",
    displayOrder: 5,
  },
  {
    id: 7,
    code: "savings",
    // Phase 46: "savings" replaces "extraordinary" — label/color sourced from NATURE_LABELS/NATURE_COLORS[extraordinary]
    directionId: 3,
    labelIt: "Straordinario",
    color: "#fbbf24",
    displayOrder: 6,
  },
  {
    id: 8,
    code: "investment",
    // Phase 46: "investment" replaces "financial" — label/color sourced from NATURE_LABELS/NATURE_COLORS[financial]
    directionId: 3,
    labelIt: "Finanziario",
    color: "#a78bfa",
    displayOrder: 7,
  },
];
